version: "3"
services:
    redis:
        image: redis
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: outline
        volumes:
            - ./postgres:/var/lib/postgresql/data
    s3:
        image: lphoward/fake-s3
        command: -r /fakes3_root -p 4569
        volumes:
            - ./fakes3:/fakes3_root
    outline:
        image: adamyordan/outline
        command: yarn start
        depends_on:
            - postgres
            - redis
            - s3
        env_file: ./.env
    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./cert/server.crt:/etc/nginx/server.crt
            - ./cert/server.key:/etc/nginx/server.key
        ports:
            - "8443:443"
        depends_on:
            - s3
            - outline